### ISSUE TITLE
fluentbit operator의 kubernetes 1.22 지원

### ISSUE THREAD

**Issue by intelliguy** [openinfradev/helm-charts#82]
# 배경
kubernetes 1.22가 되면서 api 버전들이 많이 변경되었고 operator 및 crd관련 deprecated 버전들이 발생했다.
fluentbit-operator의 경우 도입당시(2020초반) 완성도 부족의 문제와 log기반 알람을 위한 기능 등을 위해 임의의 operator를 수정해 개발했다. 선택했던 kubesphere의 fluentbit-operator는 fluent 진영에서 공식 helmchart로 포함했으며 완성도 많이 올라갔음을 확인했음
당시 작업내역
* 몇몇 버그수정
* 필요한 기능추가
> * http hook 지원
> * rewrite filter 지원

# 작업내역
k8s 1.22 버전에서 실행될 수 있도록 fluentbit관련 자원 배포방법을 재정의하고 자동화 부분등을 수정하여 완성한다.

**Comment by intelliguy** [comment]
fluentbit operator를 확인해 본 결과 기존에 수행했던 작업들이 대부분 반영된 것을 확인
* 버그수정됨
* 두개의 기능이 추가됨

문제점은 다음과 같음
* rewrite filter의 경우 master버전에만 존재
* 사용하는 형태가 우리와 다르고 몇몇 필드를 사용하지 않음

**Comment by intelliguy** [comment]
기존에 작업했던 내용
* https://github.com/intelliguy/fluentbit-operator/commit/2c7b9455a89942ace7c2ab8a9583aac6a6b8e2ae
* https://github.com/intelliguy/fluentbit-operator/commit/5174c50d79b436074c56277185270d92e5f48504
* https://github.com/intelliguy/fluentbit-operator/commit/437f0d8495c13c3f910f97d9f1008d85f9e948f6

**Comment by intelliguy** [comment]
일단 operator는 upstream을 사용하고 helmchart는 개발물을 사용하는 것으로 상정하고 테스트 중인데 이전에 발생했던 too many openfile 이슈를 만남

`bash
siim@u20-dev:~/.kube$ kubectl logs -n lma fluent-bit-ddsfp 
level=error err="too many open files"
`

**Comment by intelliguy** [comment]
aws 클러스에 생성하니 위 이슈는 발생하지 않음

**Comment by intelliguy** [comment]
https://github.com/tks-management/decapod-base-yaml/pull/8

**Comment by robertchoi80** [comment]
> aws 클러스에 생성하니 위 이슈는 발생하지 않음

그럼 다른 환경에서는 아직 발생하는 건가요? 그럼 구축형에서는 문제가 될 수 있는 게 아닌지..

**Comment by intelliguy** [comment]
기억을 더듬어보면 ubuntu의 특성으로 관련한 문제가 있었던거 같습니다.

**Comment by intelliguy** [comment]
https://github.com/openinfradev/helm-charts/issues/82

**Comment by bluejayA** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/tks-development-60c96f813019b5000e5b69c3/issues/openinfradev/helm-charts/82?planning-poker) with ZenHub @intelliguy
